name: tes-pav-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - jupyter-book
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - matplotlib
  - meshio[all]
  - pip>=20.1
  - ipykernel
  - nbconvert
  - fenics-dolfinx
  - festim=2.0b0
  - python-gmsh
  - shapely
  - scipy
  - pip:
    - pyparsing
    - h-transport-materials==0.16
    - pyvista[all,trame]  # trame cannot be installed on conda
    - gmsh