name: tes-model-env

channels:
  - conda-forge
  - defaults

dependencies:
# TODO: add OpenFoam dependencies
  - sphinx-tags
  - matplotlib
  - meshio[all]
  - pip>=20.1
  - ipykernel
  - nbconvert
  # - mshr
  - fenics-dolfinx
  - festim=2.0b0
  - python-gmsh
  - pip:
    - pyparsing
    - h-transport-materials==0.16
    - pyvista[all,trame]  # trame cannot be installed on conda
    - git+https://github.com/festim-dev/foam2dolfinx